version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: mehrshad
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: carsaledb
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - webapi_network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: shaabanimehrshad9@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - webapi_network
    restart: unless-stopped
    depends_on:
      - postgres
  redis:
    image: redis:latest
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis:/etc/redis.conf
      - redis:/data
    ports:
        - "6380:6379"
    networks:
      - webapi_network
volumes:
  postgres:
  pgadmin:
  redis:
  logs:

networks:
  webapi_network:
    driver: bridge
