version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: car_sale_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5442:5432"
    networks:
      - webapi_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: shaabanimehrshad9@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8099:80"
    networks:
      - webapi_network
    restart: unless-stopped
    depends_on:
      - postgres
  redis:
    image: redis:latest
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis:/etc/redis.conf
      - redis:/data
    ports:
        - "6597:6379"
    networks:
      - webapi_network
volumes:
  postgres:
  pgadmin:
  redis:
  logs:

networks:
  webapi_network:
    driver: bridge
